openapi: 3.0.0
info:
  description: This is Service spec for Account Services
  version: "1.0.0"
  title: Account Services

x-Application: "Account"

x-Spec: "service.yaml"

# All Our APIs
x-apis:
  AccountApi:
    depends:
      - name: AccountService
        type: Service
  WalletApi:
    depends:
      - name: WalletService
        type: Service
    exceptions:
      - BalanceException
  PortfolioApi:
    depends:
      - name: AccountService
        type: Service
      - name: PortfilioService
        type: Service

# All Our Services
x-services:
  AccountService:
    depends:
      - name: WalletService
        type: Service

      - name: AccountRepo
        type: Repo

      - name: OrderExService
        type: ExService
    interface:
      get_account_details:
        arguments:
          - name: "account_id"
            type: UUID
        returns: AccountDetails
    allow_test: True

  WalletService:
    depends:
      - name: WalletRepo
        type: Service
    interface:
      get_balace:
        arguments:
          - name: "account_id"
            type: UUID
        returns: int
    allow_test: True

# All Our Ex-Services
x-ex-services:
  OrderService:
    spec: "order_service.yaml"
    allow_test: True

# All Our Repos
x-repos:
  WalletRepo:
    crud:
      table_name: wallet
      model: Wallet
    translator: True
    allow_test: True

  AccountRepo:
    crud:
      table_name: account
      model: Account
    translator: True
    allow_test: True

  TestRepo:
    empty: True


# All Our Domain Models
components:
  schemas:
    Positions:
      type: object
      properties:
        stock:
          type: string
        symbol:
          type: string
        quantity:
          type: integer
          format: int32
          minimum : 0
        avg_buy_price:
          type: integer
          minimum : 0
        avg_sell_price:
          type: integer
          minimum: 0
      required:
        - stock
        - symbol
        - quantity
        - avg_buy_price
        - avg_sell_price

    BasicErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600

    ExtendedErrorModel:
      allOf:
        - $ref: '#/components/schemas/BasicErrorModel'
        - type: object
          required:
            - rootCause
          properties:
            rootCause:
              type: string

    AccountDetails:
      type: object
      properties:
        cash:
          type: integer
          description: Total cash in the account
        positions:
          type: object
          $ref: '#/components/schemas/Positions'
      required:
        - cash
        - positions
